server:
  port: 5000

spring:
  application:
    name: ollama-proxy
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: llama3 # Default fallback model

app:
  conversations:
    max-history-messages: 1000
    ttl: 24h
